M    XMLSchema.py -- If one tries to grab a schema item using the helper methods, if that item doesn't exist and the namespace is not in the BUILT_IN_NAMESPACES list then throw a SchemaError.  Now failure to specify an import dependency will result in an error like:
     ZSI.wstools.XMLSchema.SchemaError: schema "urn:webservices" does not import namespace "urn:base"

when "item.getTypeDefinition()" is called and the "type" attribute value QName is in a namespace that hasn't been declared as a dependency

So basically this throws errors when can't find a schema item that is supposed to be defined, rather than just returning None most of the time,  which is always an error condition.  


M a  Utility.py

-- use M2Crypto if available for TimeOutSocket, and standard "ssl" if it's not
--


git-svn-id: https://pywebsvcs.svn.sourceforge.net/svnroot/pywebsvcs/trunk@1405 7150bf37-e60d-0410-b93f-83e91ef0e581